# Generated by Django 3.0.1 on 2023-05-03 10:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0008_auto_20200416_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='dialog_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
